SELECT USER FROM DUAL;

SELECT EMPNO, EMPNAME, TITLE, MANAGER, SALARY, DNO FROM EMPLOYEE;
SELECT * FROM DEPARTMENT;
SELECT DEPTNO, DEPTNAME, FLOOR FROM DEPARTMENT;

DELETE FROM DEPARTMENT WHERE DEPTNO = 6;

DELETE FROM EMPLOYEE WHERE EMPNO = 1006;

