SELECT USER FROM DUAL;

SELECT * FROM EMPLOYEE;
SELECT * FROM DEPARTMENT;

SELECT DEPTNO, DEPTNAME, FLOOR FROM DEPARTMENT;

SELECT DEPTNO, DEPTNAME, FLOOR FROM DEPARTMENT WHERE DEPTNO = 1;

UPDATE DEPARTMENT SET DEPTNAME = '마케팅', FLOOR = 20 WHERE DEPTNO = 5;

DELETE FROM DEPARTMENT WHERE DEPTNO = 6;

INSERT INTO EMPLOYEE VALUES(1004, '윤한석', '부장', 4377, 5000000, 3);


